// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UmotaWebApp.Server.Data.Models;

namespace UmotaWebApp.Server.Data.Migrations
{
    [DbContext(typeof(UmotaMasterDbContext))]
    partial class UmotaMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisAmbar", b =>
                {
                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adi");

                    b.Property<string>("FirmaNo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("firma_no");

                    b.Property<int>("Isyeriref")
                        .HasColumnType("int")
                        .HasColumnName("isyeriref");

                    b.Property<short>("Kodu")
                        .HasColumnType("smallint")
                        .HasColumnName("kodu");

                    b.Property<int>("Logref")
                        .HasColumnType("int")
                        .HasColumnName("logref");

                    b.ToTable("sis_ambar");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisFirma", b =>
                {
                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firma_adi");

                    b.Property<string>("FirmaNo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("firma_no");

                    b.Property<bool?>("LogoCariKart")
                        .HasColumnType("bit")
                        .HasColumnName("logo_cari_kart");

                    b.Property<string>("LogoFirmaNo")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("logo_firma_no");

                    b.Property<bool?>("LogoHizmetKart")
                        .HasColumnType("bit")
                        .HasColumnName("logo_hizmet_kart");

                    b.Property<bool?>("LogoStokKart")
                        .HasColumnType("bit")
                        .HasColumnName("logo_stok_kart");

                    b.ToTable("sis_firma");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisFirmaDonem", b =>
                {
                    b.Property<string>("Aciklama")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("aciklama");

                    b.Property<short?>("FirmaNo")
                        .HasColumnType("smallint")
                        .HasColumnName("firma_no");

                    b.Property<short?>("LogoDonem")
                        .HasColumnType("smallint")
                        .HasColumnName("logo_donem");

                    b.Property<short?>("LogoFirma")
                        .HasColumnType("smallint")
                        .HasColumnName("logo_firma");

                    b.Property<int>("Logref")
                        .HasColumnType("int")
                        .HasColumnName("logref");

                    b.Property<byte?>("Ondeger")
                        .HasColumnType("tinyint")
                        .HasColumnName("ondeger");

                    b.Property<short?>("Yil")
                        .HasColumnType("smallint")
                        .HasColumnName("yil");

                    b.ToTable("sis_firma_donem");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisFirmaDonemYetki", b =>
                {
                    b.Property<int?>("Donemref")
                        .HasColumnType("int")
                        .HasColumnName("donemref");

                    b.Property<string>("Kodu")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("kodu");

                    b.Property<int>("Logref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("logref")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte?>("Tur")
                        .HasColumnType("tinyint")
                        .HasColumnName("tur");

                    b.ToTable("sis_firma_donem_yetki");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisIsyeri", b =>
                {
                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adi");

                    b.Property<string>("FirmaNo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("firma_no");

                    b.Property<short>("Kodu")
                        .HasColumnType("smallint")
                        .HasColumnName("kodu");

                    b.Property<int>("Logref")
                        .HasColumnType("int")
                        .HasColumnName("logref");

                    b.ToTable("sis_isyeri");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisKisayol", b =>
                {
                    b.Property<string>("KullaniciKodu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("kullanici_kodu");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.ToTable("sis_kisayol");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisKullanici", b =>
                {
                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kullanici_adi");

                    b.Property<bool>("KullaniciAktif")
                        .HasColumnType("bit")
                        .HasColumnName("kullanici_aktif");

                    b.Property<bool>("KullaniciIptal")
                        .HasColumnType("bit")
                        .HasColumnName("kullanici_iptal");

                    b.Property<string>("KullaniciKodu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("kullanici_kodu");

                    b.Property<int?>("KullaniciMenuProfil")
                        .HasColumnType("int")
                        .HasColumnName("kullanici_menu_profil");

                    b.Property<string>("KullaniciPcadi")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kullanici_pcadi");

                    b.Property<string>("KullaniciSifre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("kullanici_sifre");

                    b.Property<string>("KullaniciYetkiKodu")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("kullanici_yetki_kodu");

                    b.Property<string>("LogoPassword")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("logo_password");

                    b.Property<string>("LogoUsername")
                        .HasMaxLength(21)
                        .IsUnicode(false)
                        .HasColumnType("varchar(21)")
                        .HasColumnName("logo_username");

                    b.Property<string>("MailAdres")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mail_adres");

                    b.Property<string>("MailHost")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mail_host");

                    b.Property<string>("MailImza")
                        .HasColumnType("text")
                        .HasColumnName("mail_imza");

                    b.Property<string>("MailKullanici")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mail_kullanici");

                    b.Property<string>("MailSifre")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mail_sifre");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime")
                        .HasColumnName("son_giris_tarihi");

                    b.ToTable("sis_kullanici");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisKullaniciHaklari", b =>
                {
                    b.Property<string>("HakTipi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("hak_tipi")
                        .IsFixedLength(true);

                    b.Property<string>("KullaniciKodu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("kullanici_kodu");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.ToTable("sis_kullanici_haklari");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisKullaniciYetkiKodlari", b =>
                {
                    b.Property<string>("KullaniciKodu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("kullanici_kodu");

                    b.Property<string>("YetkiKodu")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("yetki_kodu");

                    b.ToTable("sis_kullanici_yetki_kodlari");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisMenuProfil", b =>
                {
                    b.Property<string>("ProfilAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("profil_adi");

                    b.Property<int>("ProfilId")
                        .HasColumnType("int")
                        .HasColumnName("profil_id");

                    b.ToTable("sis_menu_profil");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisMenuProfilHaklari", b =>
                {
                    b.Property<string>("HakTipi")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasColumnName("hak_tipi")
                        .IsFixedLength(true);

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<int>("ProfilId")
                        .HasColumnType("int")
                        .HasColumnName("profil_id");

                    b.ToTable("sis_menu_profil_haklari");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisMenuler", b =>
                {
                    b.Property<short?>("ImageIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("image_index");

                    b.Property<bool?>("MenuAcarkenGuncelle")
                        .HasColumnType("bit")
                        .HasColumnName("menu_acarken_guncelle");

                    b.Property<string>("MenuDfm")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("menu_dfm");

                    b.Property<bool?>("MenuGirismi")
                        .HasColumnType("bit")
                        .HasColumnName("menu_girismi");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<short>("MenuModul")
                        .HasColumnType("smallint")
                        .HasColumnName("menu_modul");

                    b.Property<short?>("MenuParam")
                        .HasColumnType("smallint")
                        .HasColumnName("menu_param");

                    b.Property<string>("MenuSecenek")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("menu_secenek");

                    b.Property<short?>("MenuSira")
                        .HasColumnType("smallint")
                        .HasColumnName("menu_sira");

                    b.Property<string>("MenuTanimi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("menu_tanimi");

                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.ToTable("sis_menuler");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisRefno", b =>
                {
                    b.Property<int>("Increment")
                        .HasColumnType("int")
                        .HasColumnName("increment");

                    b.Property<int>("Lastrefno")
                        .HasColumnType("int")
                        .HasColumnName("lastrefno");

                    b.Property<string>("Tablename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tablename");

                    b.ToTable("sis_refno");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisSabitler", b =>
                {
                    b.Property<byte?>("Izin")
                        .HasColumnType("tinyint")
                        .HasColumnName("izin");

                    b.Property<string>("Tanimi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tanimi");

                    b.Property<short>("Tip")
                        .HasColumnType("smallint")
                        .HasColumnName("tip");

                    b.ToTable("sis_sabitler");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisSabitlerDetay", b =>
                {
                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("adi");

                    b.Property<int?>("Ikodu")
                        .HasColumnType("int")
                        .HasColumnName("ikodu");

                    b.Property<byte?>("Izin")
                        .HasColumnType("tinyint")
                        .HasColumnName("izin");

                    b.Property<string>("Kodu")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("kodu");

                    b.Property<string>("OzelKod1")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ozel_kod1");

                    b.Property<DateTime?>("OzelKod10")
                        .HasColumnType("datetime")
                        .HasColumnName("ozel_kod10");

                    b.Property<DateTime?>("OzelKod11")
                        .HasColumnType("datetime")
                        .HasColumnName("ozel_kod11");

                    b.Property<DateTime?>("OzelKod12")
                        .HasColumnType("datetime")
                        .HasColumnName("ozel_kod12");

                    b.Property<string>("OzelKod2")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ozel_kod2");

                    b.Property<string>("OzelKod3")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ozel_kod3");

                    b.Property<int?>("OzelKod4")
                        .HasColumnType("int")
                        .HasColumnName("ozel_kod4");

                    b.Property<int?>("OzelKod5")
                        .HasColumnType("int")
                        .HasColumnName("ozel_kod5");

                    b.Property<int?>("OzelKod6")
                        .HasColumnType("int")
                        .HasColumnName("ozel_kod6");

                    b.Property<double?>("OzelKod7")
                        .HasColumnType("float")
                        .HasColumnName("ozel_kod7");

                    b.Property<double?>("OzelKod8")
                        .HasColumnType("float")
                        .HasColumnName("ozel_kod8");

                    b.Property<double?>("OzelKod9")
                        .HasColumnType("float")
                        .HasColumnName("ozel_kod9");

                    b.Property<int?>("Renk1")
                        .HasColumnType("int")
                        .HasColumnName("renk1");

                    b.Property<int?>("Renk2")
                        .HasColumnType("int")
                        .HasColumnName("renk2");

                    b.Property<int>("SabitDetayId")
                        .HasColumnType("int")
                        .HasColumnName("sabit_detay_id");

                    b.Property<short>("Siralama")
                        .HasColumnType("smallint")
                        .HasColumnName("siralama");

                    b.Property<short>("Tip")
                        .HasColumnType("smallint")
                        .HasColumnName("tip");

                    b.Property<string>("YabanciAdi")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("yabanci_adi");

                    b.ToTable("sis_sabitler_detay");
                });

            modelBuilder.Entity("UmotaWebApp.Server.Data.Models.SisYetkiKodlari", b =>
                {
                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("yetki_adi");

                    b.Property<string>("YetkiKodu")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("yetki_kodu");

                    b.ToTable("sis_yetki_kodlari");
                });
#pragma warning restore 612, 618
        }
    }
}
